export const PLANS = [
  {
    id: 1,
    name: "Residential",
    category: "residential",
    speed: "50–200 Mbps",
    priceMonthly: 120,
    hardwarePrice: 599,
    popular: false,
    active: true,
    description: "Best for homes and small properties.",
    features: ["Unlimited data", "50–200 Mbps download", "Fixed location use", "99.9% uptime SLA", "24/7 support"],
  },
  {
    id: 2,
    name: "Priority",
    category: "residential",
    speed: "40–220 Mbps",
    priceMonthly: 250,
    hardwarePrice: 599,
    popular: true,
    active: true,
    description: "Priority network access for power users.",
    features: ["1 TB priority data", "40–220 Mbps download", "Priority access during congestion", "Portable use", "24/7 priority support"],
  },
  {
    id: 3,
    name: "Mobile",
    category: "roam",
    speed: "5–150 Mbps",
    priceMonthly: 150,
    hardwarePrice: 699,
    popular: false,
    active: true,
    description: "Stay connected on the go.",
    features: ["In-motion use", "Works globally", "RVs & boats", "Pause & resume", "Mobile app control"],
  },
  {
    id: 4,
    name: "Maritime",
    category: "roam",
    speed: "40–220 Mbps",
    priceMonthly: 250,
    hardwarePrice: 2500,
    popular: false,
    active: true,
    description: "High-speed internet at sea.",
    features: ["Global ocean coverage", "Vessel-rated hardware", "40–220 Mbps", "Priority access", "Fleet management"],
  },
  {
    id: 5,
    name: "Aviation",
    category: "roam",
    speed: "10–100 Mbps",
    priceMonthly: 1500,
    hardwarePrice: 10000,
    popular: false,
    active: true,
    description: "In-flight connectivity solution.",
    features: ["In-flight coverage", "FAA-certified hardware", "Low latency", "Multiple devices", "Enterprise support"],
  },
  {
    id: 6,
    name: "Business",
    category: "business",
    speed: "40–220 Mbps",
    priceMonthly: 500,
    hardwarePrice: 2500,
    popular: false,
    active: true,
    description: "High-performance for business operations.",
    features: ["Priority access", "Commercial-grade hardware", "Multi-device support", "SLA guarantee", "Dedicated support"],
  },
  {
    id: 7,
    name: "Enterprise",
    category: "business",
    speed: "150–500 Mbps",
    priceMonthly: 5000,
    hardwarePrice: 10000,
    popular: false,
    active: true,
    description: "Enterprise-grade global connectivity.",
    features: ["Dedicated bandwidth", "Custom SLA", "Multiple terminals", "Global coverage", "24/7 enterprise support"],
  },
];
